### PR TITLE
Updated Dark theme Based on New Light Theme

### PR DESCRIPTION
**Pull request by Tloru**
With this update, you should now be able to use the dark theme in Hermes Messenger with the new updated design. This update does not fix the send button and the settings and send icon remain black. I also removed the border around most elements, and boosted the contrast a bit to compensate - personally, I think it looks a bit better.

### CODE REVIEW

**Comment by Tloru** [comment]
here's what it looks like now (it's not perfect, it's just meant to provide a quick base which can be polished off for a more professional look):
screen shot 2019-02-14 at 6 51 53 pm

**Comment by Tloru** [comment]
Well, In the last comment I accidently changed the main font to PT sans. if you want, I'll revert it, otherwise, full steam ahead ;D

**Comment by Tloru** [comment]
here's what it looks like with a sans-serif font, btw:
screen shot 2019-02-14 at 6 58 31 pm

**Comment by Tloru** [comment]
Closing this as dark theme was added separately from this merge.

**Comment by spaceface777** [comment]
@Tloru Now that we have theming support, you can propose your own theme. Take a look at the `web_client/scss/themes/` folder for the themes we have now, adding a new theme is just making another file in that folder.

**Pull request closed without merging**
