### PR TITLE
Logo Update

### PR DESCRIPTION
**Pull request by Tloru**
Added two new logos to the Logos Folder For potential use.

### CODE REVIEW

**Comment by Tloru** [comment]
closing this for now while I get my files in order....

**Comment by ThePerkinrex** [comment]
The logo is really good, and it will be merged when it's ready

**Comment by Tloru** [comment]
Leaving on vacation, Leaving pull request open if someone want to contribute.

**Comment by Tloru** [comment]
Here are the files, sorry :\. I hate to have to make you do this. 

hermesmessengerlogo

**Comment by Tloru** [comment]
Fixed it, looks ready to merge 👍

**Comment by spaceface777** [comment]
Thanks so much for the new icon! We'll merge this ASAP.

**Pull request merged**
